In [36]:
import pandas as pd
import numpy as np
import pydeck as pdk
from pydeck.types import String
import matplotlib.pyplot as plt
import os

In [37]:
os.getcwd()

'/Users/pm/Desktop/Assignments&Articles/___Medium/PY_deckgl'

In [38]:
os.listdir()

['.DS_Store', 'Untitled.ipynb', 'stores.xlsx', '.ipynb_checkpoints']

In [39]:
df = pd.read_excel('stores.xlsx')
df.set_index('Location Name')

,Address line 1,Address line 2,Address line 3,City Name,Latitude,Longitude,Lat,Long,Postal Code,Results
Location Name,,,,,,,,,,
1,NURME 2,,,HAAPSALU,58941276,23543118,58.941276,23.543118,90501,223
2,TALLINNA MNT 19A,,,KURESSAARE,58254370,22485654,58.254370,22.485654,93801,4540
3,TALLINNA MNT 17,,,RAPLA,59004412,24794158,59.004412,24.794158,79513,434
4,KESKVAELJAK 3,,,KAERDLA,58998799,22747828,58.998799,22.747828,92413,3333
5,RAE 14B,,,PALDISKI,59347516,24062579,59.347516,24.062579,76805,2000
...,...,...,...,...,...,...,...,...,...,...
63,PARNU MAANTEE 22,,,TALLINN,59431640,24745370,59.431640,24.745370,10141,3333
64,SOPRUSE PST 201,,,TALLINN,59401435,24697144,59.401435,24.697144,13401,4544
65,AIA 5,VANA VIRU 11,,TALLINN,59437640,24751110,59.437640,24.751110,10111,6455
66,MAHTRA 1,,,TALLINN,59442190,24873540,59.442190,24.873540,13811,3343
67,TUULEMAA 20A,,,TALLINN,59447380,24692640,59.447380,24.692640,10315,9872

In [40]:
df.columns

Index(['Location Name', 'Address line 1', 'Address line 2', 'Address line 3',
       'City Name', 'Latitude', 'Longitude', 'Lat', 'Long', 'Postal Code',
       'Results'],
      dtype='object')

In [41]:
df2 = df[['Location Name', 'City Name', 'Latitude', 'Longitude', 'Lat', 'Long', 'Postal Code', 'Results']]

In [42]:
df2

,Location Name,City Name,Latitude,Longitude,Lat,Long,Postal Code,Results
0,1,HAAPSALU,58941276,23543118,58.941276,23.543118,90501,223
1,2,KURESSAARE,58254370,22485654,58.254370,22.485654,93801,4540
2,3,RAPLA,59004412,24794158,59.004412,24.794158,79513,434
3,4,KAERDLA,58998799,22747828,58.998799,22.747828,92413,3333
4,5,PALDISKI,59347516,24062579,59.347516,24.062579,76805,2000
...,...,...,...,...,...,...,...,...
62,63,TALLINN,59431640,24745370,59.431640,24.745370,10141,3333
63,64,TALLINN,59401435,24697144,59.401435,24.697144,13401,4544
64,65,TALLINN,59437640,24751110,59.437640,24.751110,10111,6455
65,66,TALLINN,59442190,24873540,59.442190,24.873540,13811,3343
66,67,TALLINN,59447380,24692640,59.447380,24.692640,10315,9872

In [43]:
df2["Long"] = df2["Long"].astype(float)
df2["Lat"] = df2["Lat"].astype(float)
df2

<ipython-input-43-e435de90e376>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Long"] = df2["Long"].astype(float)
<ipython-input-43-e435de90e376>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Lat"] = df2["Lat"].astype(float)

,Location Name,City Name,Latitude,Longitude,Lat,Long,Postal Code,Results
0,1,HAAPSALU,58941276,23543118,58.941276,23.543118,90501,223
1,2,KURESSAARE,58254370,22485654,58.254370,22.485654,93801,4540
2,3,RAPLA,59004412,24794158,59.004412,24.794158,79513,434
3,4,KAERDLA,58998799,22747828,58.998799,22.747828,92413,3333
4,5,PALDISKI,59347516,24062579,59.347516,24.062579,76805,2000
...,...,...,...,...,...,...,...,...
62,63,TALLINN,59431640,24745370,59.431640,24.745370,10141,3333
63,64,TALLINN,59401435,24697144,59.401435,24.697144,13401,4544
64,65,TALLINN,59437640,24751110,59.437640,24.751110,10111,6455
65,66,TALLINN,59442190,24873540,59.442190,24.873540,13811,3343
66,67,TALLINN,59447380,24692640,59.447380,24.692640,10315,9872

In [60]:
layer = pdk.Layer(
    'ColumnLayer',
    df2,
    get_position=['Long', 'Lat'],
    get_elevation=["Results"],
    auto_highlight=True,
    elevation_scale=5,
    pickable=True,
    extruded=True,
    get_radius=100,
    get_fill_color=["Results * 10", "Results", "Results * 40", 220],
    coverage=1
)

In [61]:
# Set the viewport location
view_state = pdk.ViewState(
    longitude=25.336900,
    latitude=54.734235,
    zoom=2,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36)

In [62]:
r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.to_html('stores.html')